const checkpoint = [
  {
    url: 'https://uselessfacts.jsph.pl/random.json',
    item_name: 'Laptop',
    img_url: 'images/objects_01.png',
    number: 0,
    position: [-45, 1, -3],
    stair: '1_E_Stairs',
    collected: false,
    object: '1_E_Object',
  },
  {
    url: 'https://uselessfacts.jsph.pl/random.json',
    item_name: 'EA Socks',
    img_url: 'images/objects_02.png',
    number: 1,
    position: [-26, 2, -3],
    stair: '2_D_Stairs',
    collected: false,
    object: '2_D_Object',
  },
  {
    url: 'https://uselessfacts.jsph.pl/random.json',
    item_name: 'Soccer Ball',
    img_url: 'images/objects_03.png',
    number: 2,
    position: [-5, 1, -7],
    stair: '3_G_Stairs',
    collected: false,
    object: '3_G_Object',
  },
  {
    url: 'https://uselessfacts.jsph.pl/random.json',
    item_name: 'World Map',
    img_url: 'images/objects_04.png',
    number: 3,
    position: [21, 1, -3],
    stair: '4_A_Stairs',
    collected: false,
    object: '4_A_Object',
  },
  {
    url: 'https://uselessfacts.jsph.pl/random.json',
    item_name: 'Vynil',
    img_url: 'images/objects_05.png',
    number: 4,
    position: [33, 1, -3],
    stair: '5_R_Stairs',
    collected: false,
    object: '5_R_Object',
  },
  {
    url: 'https://uselessfacts.jsph.pl/random.json',
    item_name: 'EA mug',
    img_url: 'images/objects_06.png',
    number: 5,
    position: [-39, 1, 24],
    stair: '6_A_Stairs',
    collected: false,
    object: '6_A_Object',
  },
  {
    url: 'https://uselessfacts.jsph.pl/random.json',
    item_name: 'Spaceship',
    img_url: 'images/objects_07.png',
    number: 6,
    position: [-25, 1, 26],
    stair: '7_L_Stairs',
    collected: false,
    object: '7_L_Object',
  },
  {
    url: 'https://uselessfacts.jsph.pl/random.json',
    item_name: 'Frame',
    img_url: 'images/objects_08.png',
    number: 7,
    position: [-7, 1, 22],
    stair: '8_L_Stairs',
    collected: false,
    object: '8_L_Object',
  },
  {
    url: 'https://uselessfacts.jsph.pl/random.json',
    item_name: 'Kitty',
    img_url: 'images/objects_09.png',
    number: 8,
    position: [22, 1, 18],
    stair: '9_A_Stairs',
    collected: false,
    object: '9_A_Object',
  },
  {
    url: 'https://uselessfacts.jsph.pl/random.json',
    item_name: 'Beach Ball',
    img_url: 'images/objects_10.png',
    number: 9,
    position: [42, 2, 17],
    stair: '10_N_Stairs',
    collected: false,
    object: '10_N_Object',
  },
];

export default checkpoint;
